name: Label Core Team PRs

on:
  pull_request:

permissions:
  contents: read  # Allows reading repo content
  pull-requests: write  # Allows adding labels to PRs
  issues: write  # Allows adding labels to issues

env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  defaults:
    run:
      shell: bash
jobs:
  check_maintainer:
    uses: facebook/react/.github/workflows/shared_check_maintainer.yml@main
    permissions:
      contents: read  # Required for check_maintainer
    with:
      actor: ${{ github.event.pull_request.user.login }}
      is_remote: true
    secrets: inherit

  label:
    needs: check_maintainer
    if: ${{ needs.check_maintainer.outputs.is_core_team == 'true' }}
    if: ${{ needs.check_maintainer.result == 'true' }}
    permissions:
      issues: write  # Allows adding labels on issues
      pull-requests: write  # Allows adding labels on PRs
    steps:
      - name: Label PR as React Core Team
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              labels: ['React Core Team']
            })